apiVersion: v2
name: onecx-example-svc
version: 999-SNAPSHOT
appVersion: 999-SNAPSHOT
description: Ping quarkus
keywords:
  - ping quarkus
sources:
  - https://github.com/onecx-apps/onecx-example-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.27.0-rc.1
    repository: oci://ghcr.io/onecx/charts

      